// End-to-end run of the LensTool2 command-line tool.
//
// Runs the whole pipeline -- parse the OpticalBench prescription, build the
// model for each zoom configuration, vignette it, trace, and write all 29
// report artifacts -- then compares every one against the files committed under
// Examples/jfotoptix/canon-rf70-200mm-f2.8LZ/.
//
// No generated expectations: the reference is the repository itself. That lens
// is a recent two-configuration zoom whose committed outputs were confirmed to
// match the current Java, so it is a fair target; older Examples folders were
// generated by earlier versions and will not match.
//
// This is the slowest test in the suite (about a minute) because it really does
// run two full spot analyses per configuration, twice over. It earns that by
// being the only test that exercises the tool exactly as a user does.
#include "TestHarness.h"

#include "redukti/tools/LensTool2.h"
#include "redukti/util/Args.h"

#include <cctype>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <set>
#include <string>
#include <vector>

namespace {

namespace fs = std::filesystem;
using redukti::tools::LensTool2;
using redukti::util::Args;

const char *const REF_DIR = REDUKTI_EXAMPLES_DIR "canon-rf70-200mm-f2.8LZ/";
const char *const SPEC_NAME = "US20250155694_Example01P.txt";

/**
 * The artifacts that come out bit-identical.
 *
 * Everything on the deterministic side of the port: the exported lens, every
 * layout, every spot diagram, the MTF data, and the text dumps.
 */
const char *const EXACT_FILES[] = {
    "US20250155694_Example01P.zmx",
    "layout-0.svg",        "layout-1.svg",
    "layout-fan-0.svg",    "layout-fan-1.svg",
    "layoutonly-0.svg",    "layoutonly-1.svg",
    "mtf-0.csv",           "mtf-1.csv",
    "mtf-w-0.csv",         "mtf-w-1.csv",
    "paraxial-0.txt",      "paraxial-1.txt",
    "prescription.txt",
    "spot-0.svg",          "spot-1.svg",
    "spot-semi-skew-0.svg", "spot-semi-skew-1.svg",
    "spot-skew-0.svg",     "spot-skew-1.svg",
    "vig-0.txt",           "vig-1.txt",
};

/**
 * The artifacts that carry the hexapolar sin/cos divergence.
 *
 * SpotOptions defaults to the hexapolar pattern, whose ring points come from
 * sin/cos; JDK 25 and MSVC disagree on a handful of them by 1-2 ulps (see
 * cpp-port-ground-truth-workflow). The spot radii inherit that at about 1e-14
 * relative, and it occasionally tips a plotted SVG coordinate across the 0.001
 * rounding boundary DecimalFormat uses -- hence one unit in the last printed
 * place. Structure still has to match exactly.
 */
const char *const APPROX_FILES[] = {
    "mtf-0.svg", "mtf-1.svg", "mtf-w-0.svg", "mtf-w-1.svg",
    "spot-report-0.txt", "spot-report-1.txt",
};

std::string readFile(const std::string &path) {
    std::ifstream in(path, std::ios::binary);
    CHECK(in.good());
    std::string s((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
    // The committed files use bare newlines; normalise in case of checkout
    // translation so the comparison is about content, not line endings.
    std::string out;
    for (std::size_t i = 0; i < s.size(); i++) {
        if (s[i] == '\r' && i + 1 < s.size() && s[i + 1] == '\n')
            continue;
        out.push_back(s[i]);
    }
    return out;
}

std::vector<std::string> lines(const std::string &text) {
    std::vector<std::string> out;
    std::size_t start = 0;
    while (start < text.size()) {
        auto nl = text.find('\n', start);
        if (nl == std::string::npos) {
            out.push_back(text.substr(start));
            break;
        }
        out.push_back(text.substr(start, nl - start));
        start = nl + 1;
    }
    while (!out.empty() && out.back().empty())
        out.pop_back();
    return out;
}

/** Splits a line into its non-numeric skeleton and the numbers it contains. */
void splitNums(const std::string &s, std::string &skeleton, std::vector<double> &nums) {
    std::size_t i = 0;
    while (i < s.size()) {
        std::size_t j = i;
        if (s[j] == '-' || s[j] == '+')
            j++;
        std::size_t d0 = j;
        while (j < s.size() && std::isdigit(static_cast<unsigned char>(s[j])))
            j++;
        bool any = j > d0;
        if (j < s.size() && s[j] == '.') {
            j++;
            while (j < s.size() && std::isdigit(static_cast<unsigned char>(s[j]))) {
                j++;
                any = true;
            }
        }
        if (any && j < s.size() && (s[j] == 'E' || s[j] == 'e')) {
            std::size_t k = j + 1;
            if (k < s.size() && (s[k] == '-' || s[k] == '+'))
                k++;
            std::size_t e0 = k;
            while (k < s.size() && std::isdigit(static_cast<unsigned char>(s[k])))
                k++;
            if (k > e0)
                j = k;
        }
        if (any) {
            nums.push_back(std::strtod(s.substr(i, j - i).c_str(), nullptr));
            skeleton += '#';
            i = j;
        } else {
            skeleton += s[i];
            i++;
        }
    }
}

void compareExact(const std::string &mine, const std::string &ref,
                  const std::string &name) {
    auto a = lines(readFile(mine));
    auto b = lines(readFile(ref));
    if (a.size() != b.size())
        ::redukti::test::reportFailure(__FILE__, __LINE__,
                                       name + ": got " + std::to_string(a.size()) +
                                           " lines, want " + std::to_string(b.size()));
    for (std::size_t i = 0; i < a.size() && i < b.size(); i++) {
        if (a[i] != b[i]) {
            ::redukti::test::reportFailure(__FILE__, __LINE__,
                                           name + " line " + std::to_string(i + 1) +
                                               ": got \"" + a[i] + "\" want \"" + b[i] +
                                               "\"");
            return; // one report per file is enough to locate the drift
        }
    }
}

void compareApprox(const std::string &mine, const std::string &ref,
                   const std::string &name, double atol, double rtol) {
    auto a = lines(readFile(mine));
    auto b = lines(readFile(ref));
    if (a.size() != b.size())
        ::redukti::test::reportFailure(__FILE__, __LINE__,
                                       name + ": got " + std::to_string(a.size()) +
                                           " lines, want " + std::to_string(b.size()));
    for (std::size_t i = 0; i < a.size() && i < b.size(); i++) {
        std::string sa, sb;
        std::vector<double> na, nb;
        splitNums(a[i], sa, na);
        splitNums(b[i], sb, nb);
        if (sa != sb) {
            ::redukti::test::reportFailure(__FILE__, __LINE__,
                                           name + " line " + std::to_string(i + 1) +
                                               ": structure differs");
            return;
        }
        if (na.size() != nb.size()) {
            ::redukti::test::reportFailure(__FILE__, __LINE__,
                                           name + " line " + std::to_string(i + 1) +
                                               ": number count differs");
            return;
        }
        for (std::size_t k = 0; k < na.size(); k++) {
            double tol = atol + rtol * std::abs(nb[k]);
            if (!(std::abs(na[k] - nb[k]) <= tol)) {
                ::redukti::test::reportFailure(
                    __FILE__, __LINE__,
                    name + " line " + std::to_string(i + 1) + ": got " +
                        std::to_string(na[k]) + " want " + std::to_string(nb[k]));
                return;
            }
        }
    }
}

} // namespace

TEST(lenstool2_reproduces_committed_example) {
    // Work in a scratch directory: the tool writes the .zmx next to the spec
    // file regardless of --outdir, so running it against the repository copy
    // would overwrite a committed file.
    fs::path work = fs::path(REDUKTI_TEST_TMPDIR) / "lenstool2";
    std::error_code ec;
    fs::remove_all(work, ec);
    fs::create_directories(work, ec);
    CHECK(!ec);
    fs::copy_file(fs::path(REF_DIR) / SPEC_NAME, work / SPEC_NAME,
                  fs::copy_options::overwrite_existing, ec);
    CHECK(!ec);

    Args arguments;
    arguments.specfile = (work / SPEC_NAME).string();
    // A fixed date so the README is reproducible; the Java stamps
    // LocalDate.now() here, which is why the tool takes it as a parameter.
    LensTool2::run(arguments, "2026-08-26");

    for (const char *f : EXACT_FILES)
        compareExact((work / f).string(), std::string(REF_DIR) + f, f);

    // One unit in the last printed place of an SVG coordinate is 1e-3; the spot
    // radii differ at about 1e-14 relative.
    for (const char *f : APPROX_FILES)
        compareApprox((work / f).string(), std::string(REF_DIR) + f, f, 1.1e-3, 1e-12);

    // README: identical apart from the generation date, which the reference
    // carries from the day it was produced.
    auto mineReadme = lines(readFile((work / "README.md").string()));
    auto refReadme = lines(readFile(std::string(REF_DIR) + "README.md"));
    CHECK_EQ(mineReadme.size(), refReadme.size());
    for (std::size_t i = 0; i < mineReadme.size() && i < refReadme.size(); i++)
        CHECK_STR_EQ(mineReadme[i], refReadme[i]);
}
