// Expectations generated by running java.lang.Double.toString on JDK 25.
// Digits come from Ryu; see the note in Text.h about where this intentionally
// diverges from the JDK.
#include "TestHarness.h"

#include "redukti/Text.h"

#include <limits>

using redukti::doubleToString;

TEST(doubleToString_matches_jdk) {
    CHECK_STR_EQ(doubleToString(0.0), "0.0");
    CHECK_STR_EQ(doubleToString(-0.0), "-0.0");
    CHECK_STR_EQ(doubleToString(1.0), "1.0");
    CHECK_STR_EQ(doubleToString(-1.0), "-1.0");
    CHECK_STR_EQ(doubleToString(0.5), "0.5");
    CHECK_STR_EQ(doubleToString(100.0), "100.0");
    CHECK_STR_EQ(doubleToString(1234567.0), "1234567.0");
    CHECK_STR_EQ(doubleToString(12345678.0), "1.2345678E7");
    CHECK_STR_EQ(doubleToString(0.001), "0.001");
    CHECK_STR_EQ(doubleToString(1e-4), "1.0E-4");
    CHECK_STR_EQ(doubleToString(1e7), "1.0E7");
    CHECK_STR_EQ(doubleToString(1e-7), "1.0E-7");
    CHECK_STR_EQ(doubleToString(9999999.0), "9999999.0");
    CHECK_STR_EQ(doubleToString(1.0 / 3.0), "0.3333333333333333");
    CHECK_STR_EQ(doubleToString(2.0 / 3.0), "0.6666666666666666");
    CHECK_STR_EQ(doubleToString(3.141592653589793), "3.141592653589793");
    CHECK_STR_EQ(doubleToString(2.718281828459045), "2.718281828459045");
    CHECK_STR_EQ(doubleToString(1.4142135623730951), "1.4142135623730951");
    CHECK_STR_EQ(doubleToString(1e300), "1.0E300");
    CHECK_STR_EQ(doubleToString(1e-300), "1.0E-300");
    CHECK_STR_EQ(doubleToString(123.456), "123.456");
    CHECK_STR_EQ(doubleToString(-123.456), "-123.456");
    CHECK_STR_EQ(doubleToString(1e21), "1.0E21");
    CHECK_STR_EQ(doubleToString(std::numeric_limits<double>::max()),
                 "1.7976931348623157E308");
    CHECK_STR_EQ(doubleToString(0.1), "0.1");
    CHECK_STR_EQ(doubleToString(0.2), "0.2");
    CHECK_STR_EQ(doubleToString(0.3), "0.3");
    CHECK_STR_EQ(doubleToString(1e6), "1000000.0");
    CHECK_STR_EQ(doubleToString(0.01), "0.01");
    CHECK_STR_EQ(doubleToString(2.5e-5), "2.5E-5");
    CHECK_STR_EQ(doubleToString(6.02214076e23), "6.02214076E23");
}

TEST(doubleToString_non_finite) {
    CHECK_STR_EQ(doubleToString(std::numeric_limits<double>::quiet_NaN()), "NaN");
    CHECK_STR_EQ(doubleToString(std::numeric_limits<double>::infinity()), "Infinity");
    CHECK_STR_EQ(doubleToString(-std::numeric_limits<double>::infinity()),
                 "-Infinity");
}

TEST(doubleToString_subnormal_diverges_from_jdk) {
    // Documented divergence: the JDK widens its candidate set when the shortest
    // form has one significant digit and prints 4.9E-324. Ryu gives the genuine
    // shortest round-tripping decimal. Both parse back to the same double.
    CHECK_STR_EQ(doubleToString(std::numeric_limits<double>::denorm_min()),
                 "5.0E-324");
}

// ---------------------------------------------------------------------------
// Java's %g, which the first-order and third-order reports are built from.
// Expectations dumped from String.format("%12.4g", ...) on JDK 25.
// ---------------------------------------------------------------------------
TEST(formatG_matches_java) {
    struct Row { double v; const char *want; };
    static const Row rows[] = {
        {0.0, "       0.000"},
        {1.0, "       1.000"},
        {100.0, "       100.0"},
        {100.5, "       100.5"},
        {1234.5678, "        1235"},
        {0.001, "    0.001000"},
        {1e-4, "   0.0001000"},
        {1e-5, "   1.000e-05"},
        {1e7, "   1.000e+07"},
        {1.23456789e8, "   1.235e+08"},
        {-50.0, "      -50.00"},
        {1e10, "   1.000e+10"},
        {1e-10, "   1.000e-10"},
        {0.5, "      0.5000"},
        {587.5618, "       587.6"},
        {1e100, "  1.000e+100"},
        {-1e-100, " -1.000e-100"},
        {2.0 / 3.0, "      0.6667"},
        // Rounds up to 1.000e-4, which is inside the decimal range.
        {9.99999e-5, "   0.0001000"},
        {123456.0, "   1.235e+05"},
    };
    for (const Row &r : rows)
        CHECK_STR_EQ(redukti::formatG(r.v, 12, 4), r.want);

    CHECK_STR_EQ(redukti::formatG(std::numeric_limits<double>::quiet_NaN(), 12, 4),
                 "         NaN");
    CHECK_STR_EQ(redukti::formatG(std::numeric_limits<double>::infinity(), 12, 4),
                 "    Infinity");
}
