// Expectations generated by running java.lang.Double.toString on JDK 25.
// Digits come from Ryu; see the note in Text.h about where this intentionally
// diverges from the JDK.
#include "TestHarness.h"

#include "redukti/Text.h"

#include <limits>

using redukti::doubleToString;

TEST(doubleToString_matches_jdk) {
    CHECK_STR_EQ(doubleToString(0.0), "0.0");
    CHECK_STR_EQ(doubleToString(-0.0), "-0.0");
    CHECK_STR_EQ(doubleToString(1.0), "1.0");
    CHECK_STR_EQ(doubleToString(-1.0), "-1.0");
    CHECK_STR_EQ(doubleToString(0.5), "0.5");
    CHECK_STR_EQ(doubleToString(100.0), "100.0");
    CHECK_STR_EQ(doubleToString(1234567.0), "1234567.0");
    CHECK_STR_EQ(doubleToString(12345678.0), "1.2345678E7");
    CHECK_STR_EQ(doubleToString(0.001), "0.001");
    CHECK_STR_EQ(doubleToString(1e-4), "1.0E-4");
    CHECK_STR_EQ(doubleToString(1e7), "1.0E7");
    CHECK_STR_EQ(doubleToString(1e-7), "1.0E-7");
    CHECK_STR_EQ(doubleToString(9999999.0), "9999999.0");
    CHECK_STR_EQ(doubleToString(1.0 / 3.0), "0.3333333333333333");
    CHECK_STR_EQ(doubleToString(2.0 / 3.0), "0.6666666666666666");
    CHECK_STR_EQ(doubleToString(3.141592653589793), "3.141592653589793");
    CHECK_STR_EQ(doubleToString(2.718281828459045), "2.718281828459045");
    CHECK_STR_EQ(doubleToString(1.4142135623730951), "1.4142135623730951");
    CHECK_STR_EQ(doubleToString(1e300), "1.0E300");
    CHECK_STR_EQ(doubleToString(1e-300), "1.0E-300");
    CHECK_STR_EQ(doubleToString(123.456), "123.456");
    CHECK_STR_EQ(doubleToString(-123.456), "-123.456");
    CHECK_STR_EQ(doubleToString(1e21), "1.0E21");
    CHECK_STR_EQ(doubleToString(std::numeric_limits<double>::max()),
                 "1.7976931348623157E308");
    CHECK_STR_EQ(doubleToString(0.1), "0.1");
    CHECK_STR_EQ(doubleToString(0.2), "0.2");
    CHECK_STR_EQ(doubleToString(0.3), "0.3");
    CHECK_STR_EQ(doubleToString(1e6), "1000000.0");
    CHECK_STR_EQ(doubleToString(0.01), "0.01");
    CHECK_STR_EQ(doubleToString(2.5e-5), "2.5E-5");
    CHECK_STR_EQ(doubleToString(6.02214076e23), "6.02214076E23");
}

TEST(doubleToString_non_finite) {
    CHECK_STR_EQ(doubleToString(std::numeric_limits<double>::quiet_NaN()), "NaN");
    CHECK_STR_EQ(doubleToString(std::numeric_limits<double>::infinity()), "Infinity");
    CHECK_STR_EQ(doubleToString(-std::numeric_limits<double>::infinity()),
                 "-Infinity");
}

TEST(doubleToString_subnormal_diverges_from_jdk) {
    // Documented divergence: the JDK widens its candidate set when the shortest
    // form has one significant digit and prints 4.9E-324. Ryu gives the genuine
    // shortest round-tripping decimal. Both parse back to the same double.
    CHECK_STR_EQ(doubleToString(std::numeric_limits<double>::denorm_min()),
                 "5.0E-324");
}
